apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: skills-eks-cluster
  region: ap-northeast-2
  version: "1.29"

secretsEncryption:
  keyARN: kms_arn

cloudWatch:
  clusterLogging:
    enableTypes: ["*"]

iam:
  withOIDC: true
  serviceAccounts:
    - metadata:
        name: aws-load-balancer-controller
        namespace: kube-system
      wellKnownPolicies:
        awsLoadBalancerController: true
    - metadata:
        name: cert-manager
        namespace: cert-manager
      wellKnownPolicies:
        certManager: true
vpc:
  securityGroup: sg_id # https 통신
  subnets:
    public:
      ap-northeast-2a: { id: public_a }
      ap-northeast-2b: { id: public_b }
    private:
      ap-northeast-2a: { id: private_a }
      ap-northeast-2b: { id: private_a }
  clusterEndpoints:
    publicAccess: false
    privateAccess: true

managedNodeGroups:
  - name: skills-eks-app-nodegroup
    instanceName: skills-eks-app-node
    instanceType: t4g.large
    desiredCapacity: 2
    minSize: 2
    maxSize: 10

  - name: skills-eks-addon-nodegroup
    instanceName: skills-eks-addon-node
    instanceType: m6.large
    desiredCapacity: 2
    minSize: 2
    maxSize: 10

fargateProfiles:
  - name: skills-eks-app-profile
    selectors:
      - namespace: skills
        labels:
          app: token
