apiVersion: apps/v1
kind: Deployment
metadata:
  name: token
  namespace: skills
  labels:
    app: token
spec:
  replicas: 2
  selector:
    matchLabels:
      app: token
  template:
    metadata:
      labels:
        app: token
    spec:
      containers:
        - name: token
          image: 362708816803.dkr.ecr.ap-northeast-2.amazonaws.com/token:latest
          ports:
            - containerPort: 8080
          env:
            - name: REDIS_HOST
              valueFrom:
                secretKeyRef:
                  name: token
                  key: REDIS_HOST
            - name: REDIS_PORT
              valueFrom:
                secretKeyRef:
                  name: token
                  key: REDIS_PORT
