apiVersion: v1
kind: Service
metadata:
  name: token
  namespace: skills
spec:
  selector:
    app: token
  type: ClusterIP
  sessionAffinity: None
  sessionAffinityConfig:
    clientIP:
      timeoutSeconds: 10800
  ports:
    - name: token
      protocol: TCP
      port: 8080
      targetPort: 8080
