apiVersion: apps/v1
kind: Deployment
metadata:
  name: user
  namespace: skills
  labels:
    app: user
spec:
  replicas: 2
  selector:
    matchLabels:
      app: user
  template:
    metadata:
      labels:
        app: user
    spec:
      nodeSelector:
        eks.amazonaws.com/nodegroup: skills-eks-app-nodegroup
      containers:
        - name: user
          image: 362708816803.dkr.ecr.ap-northeast-2.amazonaws.com/user:latest
          resources:
            requests:
              cpu: 100m
              memory: 100Mi
            limits:
              cpu: 100m
              memory: 100Mi
          env:
            - name: MONGODB_HOST
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: MONGODB_HOST
            - name: MONGODB_PORT
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: MONGODB_PORT
            - name: MONGODB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: MONGODB_USERNAME
            - name: MONGODB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: MONGODB_PASSWORD
            - name: AWS_REGION
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: AWS_REGION
            - name: AWS_SECRET_NAME
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: AWS_SECRET_NAME
            - name: TOKEN_ENDPOINT
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: TOKEN_ENDPOINT
          livenessProbe:
            tcpSocket:
              port: 8080
            initialDelaySeconds: 5
            timeoutSeconds: 5
          readinessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 5
            timeoutSeconds: 2
